version: '3.9'

services:
  eureka-server:
    image: sd-eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    restart: always
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

  config-server:
    image: sd-config-server:latest
    container_name: config-server
    ports:
      - "7777:7777"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    restart: always

#  gateway-service:
#    image: sd-gateway-service:latest
#    container_name: gateway-service
#    ports:
#      - "3030:3030"
#    depends_on:
#      - eureka-server
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
#    restart: always
