spring.application.name=sd-auth-server
server.port=9090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#spring.config.import=configserver:http://localhost:7777/

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres-auth:5432/sd_auth
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.authorizationserver.endpoint.authorization-uri=/oauth2/authorize
spring.security.oauth2.authorizationserver.endpoint.token-uri=/oauth2/token
spring.security.oauth2.authorizationserver.endpoint.jwk-set-uri=/oauth2/jwks

#spring.jpa.show-sql=true
#spring.jpa.generate-ddl=true
#spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG